#--------------------------------------------------------------------------------------------------#
# @author: Kaushik Biswas                                                                          #
# @version: 1.0.2                                                                                  #
# @Created by: Qt User Interface Compiler version 5.15.1                                           #
#--------------------------------------------------------------------------------------------------#


#   Library Imports
#--------------------------------------------------------------------------------------------------#
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


#   Local Imports
#--------------------------------------------------------------------------------------------------#
import UiResource


class Ui_AlohaMora(object):
    def setupUi(self, AlohaMora):
        if not AlohaMora.objectName():
            AlohaMora.setObjectName(u"AlohaMora")
        AlohaMora.resize(1933, 820)
        self.centralwidget = QWidget(AlohaMora)
        self.centralwidget.setObjectName(u"centralwidget")
        self.outer_layout = QHBoxLayout(self.centralwidget)
        self.outer_layout.setSpacing(0)
        self.outer_layout.setObjectName(u"outer_layout")
        self.outer_layout.setContentsMargins(10, 10, 10, 10)
        self.outer_frame = QFrame(self.centralwidget)
        self.outer_frame.setObjectName(u"outer_frame")
        self.outer_frame.setMinimumSize(QSize(1300, 1000))
        self.outer_frame.setStyleSheet(u"background-color: rgb(160, 205, 212);border-radius:15px;")
        self.outer_frame.setFrameShape(QFrame.NoFrame)
        self.outer_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.outer_frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.top_frame_container = QFrame(self.outer_frame)
        self.top_frame_container.setObjectName(u"top_frame_container")
        self.top_frame_container.setMinimumSize(QSize(0, 100))
        self.top_frame_container.setMaximumSize(QSize(16777215, 120))
        self.top_frame_container.setStyleSheet(u"background-color: rgb(240, 247, 245);")
        self.top_frame_container.setFrameShape(QFrame.NoFrame)
        self.top_frame_container.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.top_frame_container)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.top_frame = QFrame(self.top_frame_container)
        self.top_frame.setObjectName(u"top_frame")
        self.top_frame.setStyleSheet(u"")
        self.top_frame.setFrameShape(QFrame.NoFrame)
        self.top_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.top_frame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.top_logo_frame = QFrame(self.top_frame)
        self.top_logo_frame.setObjectName(u"top_logo_frame")
        self.top_logo_frame.setCursor(QCursor(Qt.ClosedHandCursor))
        self.top_logo_frame.setStyleSheet(u"background-color:none;border:none;")
        self.top_logo_frame.setFrameShape(QFrame.NoFrame)
        self.top_logo_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.top_logo_frame)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(20, -1, -1, -1)
        self.logo_label = QLabel(self.top_logo_frame)
        self.logo_label.setObjectName(u"logo_label")
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 71, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient = QLinearGradient(0, 0, 1, 1)
        gradient.setSpread(QGradient.PadSpread)
        gradient.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush1 = QBrush(gradient)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        gradient1 = QLinearGradient(0, 0, 1, 1)
        gradient1.setSpread(QGradient.PadSpread)
        gradient1.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient1.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush2 = QBrush(gradient1)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        gradient2 = QLinearGradient(0, 0, 1, 1)
        gradient2.setSpread(QGradient.PadSpread)
        gradient2.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient2.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush3 = QBrush(gradient2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        brush4 = QBrush(QColor(0, 0, 71, 128))
        brush4.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        gradient3 = QLinearGradient(0, 0, 1, 1)
        gradient3.setSpread(QGradient.PadSpread)
        gradient3.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient3.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush5 = QBrush(gradient3)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        gradient4 = QLinearGradient(0, 0, 1, 1)
        gradient4.setSpread(QGradient.PadSpread)
        gradient4.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient4.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush6 = QBrush(gradient4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        gradient5 = QLinearGradient(0, 0, 1, 1)
        gradient5.setSpread(QGradient.PadSpread)
        gradient5.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient5.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush7 = QBrush(gradient5)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        brush8 = QBrush(QColor(0, 0, 71, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        gradient6 = QLinearGradient(0, 0, 1, 1)
        gradient6.setSpread(QGradient.PadSpread)
        gradient6.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient6.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush9 = QBrush(gradient6)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        gradient7 = QLinearGradient(0, 0, 1, 1)
        gradient7.setSpread(QGradient.PadSpread)
        gradient7.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient7.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush10 = QBrush(gradient7)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        gradient8 = QLinearGradient(0, 0, 1, 1)
        gradient8.setSpread(QGradient.PadSpread)
        gradient8.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient8.setColorAt(0.386364, QColor(249, 249, 249, 165))
        brush11 = QBrush(gradient8)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        brush12 = QBrush(QColor(0, 0, 71, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.logo_label.setPalette(palette)
        font = QFont()
        font.setFamily(u"Century Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.logo_label.setFont(font)
        self.logo_label.setStyleSheet(u"color: rgb(0, 0, 71);")

        self.horizontalLayout_4.addWidget(self.logo_label)

        self.top_empty_label = QLabel(self.top_logo_frame)
        self.top_empty_label.setObjectName(u"top_empty_label")

        self.horizontalLayout_4.addWidget(self.top_empty_label)


        self.horizontalLayout_2.addWidget(self.top_logo_frame)

        self.top_button_frame = QFrame(self.top_frame)
        self.top_button_frame.setObjectName(u"top_button_frame")
        self.top_button_frame.setMinimumSize(QSize(80, 0))
        self.top_button_frame.setMaximumSize(QSize(100, 16777215))
        self.top_button_frame.setAutoFillBackground(False)
        self.top_button_frame.setStyleSheet(u"background-color: none;border:none;")
        self.top_button_frame.setFrameShape(QFrame.NoFrame)
        self.top_button_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.top_button_frame)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.maximize_button = QPushButton(self.top_button_frame)
        self.maximize_button.setObjectName(u"maximize_button")
        self.maximize_button.setMinimumSize(QSize(20, 20))
        self.maximize_button.setMaximumSize(QSize(20, 20))
        self.maximize_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.maximize_button.setStyleSheet(u"QPushButton{background-color: rgb(5, 182, 2);border-radius: 10px;}QPushButton:hover{background-color: rgb(3, 121, 1);}")

        self.horizontalLayout_9.addWidget(self.maximize_button, 0, Qt.AlignTop)

        self.minimize_button = QPushButton(self.top_button_frame)
        self.minimize_button.setObjectName(u"minimize_button")
        self.minimize_button.setMinimumSize(QSize(20, 20))
        self.minimize_button.setMaximumSize(QSize(20, 20))
        self.minimize_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.minimize_button.setStyleSheet(u"QPushButton{background-color: rgb(234, 202, 75);border-radius: 10px;}QPushButton:hover{background-color: rgb(150, 126, 48);}")

        self.horizontalLayout_9.addWidget(self.minimize_button, 0, Qt.AlignTop)

        self.close_button = QPushButton(self.top_button_frame)
        self.close_button.setObjectName(u"close_button")
        self.close_button.setMinimumSize(QSize(20, 20))
        self.close_button.setMaximumSize(QSize(20, 20))
        self.close_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.close_button.setStyleSheet(u"QPushButton{background-color: rgb(213, 82, 21);border-radius: 10px;}QPushButton:hover{background-color: rgb(167, 64, 16);}")

        self.horizontalLayout_9.addWidget(self.close_button, 0, Qt.AlignTop)


        self.horizontalLayout_2.addWidget(self.top_button_frame)


        self.horizontalLayout_3.addWidget(self.top_frame)


        self.verticalLayout.addWidget(self.top_frame_container)

        self.middle_stack = QStackedWidget(self.outer_frame)
        self.middle_stack.setObjectName(u"middle_stack")
        self.middle_stack.setStyleSheet(u"")
        self.login_page = QWidget()
        self.login_page.setObjectName(u"login_page")
        self.login_page.setStyleSheet(u"")
        self.horizontalLayout = QHBoxLayout(self.login_page)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.login_frame = QFrame(self.login_page)
        self.login_frame.setObjectName(u"login_frame")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_frame.sizePolicy().hasHeightForWidth())
        self.login_frame.setSizePolicy(sizePolicy)
        self.login_frame.setMaximumSize(QSize(16777215, 16777215))
        self.login_frame.setStyleSheet(u"")
        self.login_frame.setFrameShape(QFrame.NoFrame)
        self.login_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.login_frame)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.login_input_frame = QFrame(self.login_frame)
        self.login_input_frame.setObjectName(u"login_input_frame")
        self.login_input_frame.setMinimumSize(QSize(380, 450))
        self.login_input_frame.setMaximumSize(QSize(380, 450))
        self.login_input_frame.setStyleSheet(u"background-color: rgb(240, 247, 245);border-radius:15px;")
        self.login_input_frame.setFrameShape(QFrame.NoFrame)
        self.login_input_frame.setFrameShadow(QFrame.Raised)
        self.login_button = QPushButton(self.login_input_frame)
        self.login_button.setObjectName(u"login_button")
        self.login_button.setGeometry(QRect(140, 330, 100, 60))
        self.login_button.setMinimumSize(QSize(100, 60))
        self.login_button.setMaximumSize(QSize(100, 60))
        font1 = QFont()
        font1.setFamily(u"Century Gothic")
        font1.setPointSize(12)
        font1.setBold(False)
        font1.setWeight(50)
        self.login_button.setFont(font1)
        self.login_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.login_button.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(196, 220, 236);}QPushButton:hover{background-color: rgb(172, 193, 207);}")
        self.login_password = QLineEdit(self.login_input_frame)
        self.login_password.setObjectName(u"login_password")
        self.login_password.setGeometry(QRect(90, 285, 200, 25))
        self.login_password.setMinimumSize(QSize(200, 0))
        self.login_password.setMaximumSize(QSize(200, 30))
        font2 = QFont()
        font2.setFamily(u"Century Gothic")
        self.login_password.setFont(font2)
        self.login_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-bottom:1px solid #000047;}")
        self.login_password.setEchoMode(QLineEdit.Password)
        self.login_password.setAlignment(Qt.AlignCenter)
        self.user_email_input = QLineEdit(self.login_input_frame)
        self.user_email_input.setObjectName(u"user_email_input")
        self.user_email_input.setGeometry(QRect(60, 250, 260, 25))
        self.user_email_input.setMinimumSize(QSize(260, 0))
        self.user_email_input.setMaximumSize(QSize(260, 30))
        self.user_email_input.setFont(font2)
        self.user_email_input.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-bottom:1px solid #000047;}")
        self.user_email_input.setAlignment(Qt.AlignCenter)
        self.user_email_input.setReadOnly(False)
        self.user_icon_label = QLabel(self.login_input_frame)
        self.user_icon_label.setObjectName(u"user_icon_label")
        self.user_icon_label.setGeometry(QRect(90, 0, 200, 180))
        self.user_icon_label.setPixmap(QPixmap(u":/user_icon/resource/red_user.svg"))
        self.user_icon_label.setScaledContents(True)
        self.login_welcome = QLabel(self.login_input_frame)
        self.login_welcome.setObjectName(u"login_welcome")
        self.login_welcome.setGeometry(QRect(0, 180, 380, 60))
        font3 = QFont()
        font3.setFamily(u"Century Gothic")
        font3.setPointSize(18)
        self.login_welcome.setFont(font3)
        self.login_welcome.setStyleSheet(u"color: rgb(0, 0, 71);")
        self.login_welcome.setAlignment(Qt.AlignCenter)
        self.signup_option = QLabel(self.login_input_frame)
        self.signup_option.setObjectName(u"signup_option")
        self.signup_option.setGeometry(QRect(90, 410, 200, 20))
        self.signup_option.setFont(font2)
        self.signup_option.setCursor(QCursor(Qt.PointingHandCursor))
        self.signup_option.setStyleSheet(u"color: rgb(0, 0, 71);")
        self.signup_option.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.login_input_frame, 0, Qt.AlignHCenter)


        self.horizontalLayout.addWidget(self.login_frame, 0, Qt.AlignVCenter)

        self.middle_stack.addWidget(self.login_page)
        self.signup_page = QWidget()
        self.signup_page.setObjectName(u"signup_page")
        self.horizontalLayout_5 = QHBoxLayout(self.signup_page)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.signup_frame = QFrame(self.signup_page)
        self.signup_frame.setObjectName(u"signup_frame")
        self.signup_frame.setFrameShape(QFrame.NoFrame)
        self.signup_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.signup_frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.signup_input_frame = QFrame(self.signup_frame)
        self.signup_input_frame.setObjectName(u"signup_input_frame")
        self.signup_input_frame.setMinimumSize(QSize(380, 500))
        self.signup_input_frame.setMaximumSize(QSize(380, 500))
        self.signup_input_frame.setStyleSheet(u"background-color: rgb(240, 247, 245);border-radius:15px;")
        self.signup_input_frame.setFrameShape(QFrame.NoFrame)
        self.signup_input_frame.setFrameShadow(QFrame.Raised)
        self.signup_button = QPushButton(self.signup_input_frame)
        self.signup_button.setObjectName(u"signup_button")
        self.signup_button.setGeometry(QRect(140, 420, 100, 60))
        self.signup_button.setMinimumSize(QSize(100, 60))
        self.signup_button.setMaximumSize(QSize(100, 60))
        self.signup_button.setSizeIncrement(QSize(0, 0))
        font4 = QFont()
        font4.setFamily(u"Century Gothic")
        font4.setPointSize(10)
        font4.setBold(False)
        font4.setWeight(50)
        self.signup_button.setFont(font4)
        self.signup_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.signup_button.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(196, 220, 236);}QPushButton:hover{background-color: rgb(172, 193, 207);}")
        self.signup_first_password = QLineEdit(self.signup_input_frame)
        self.signup_first_password.setObjectName(u"signup_first_password")
        self.signup_first_password.setGeometry(QRect(90, 330, 200, 25))
        self.signup_first_password.setMinimumSize(QSize(200, 0))
        self.signup_first_password.setMaximumSize(QSize(200, 30))
        self.signup_first_password.setFont(font2)
        self.signup_first_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-bottom:1px solid #000047;}")
        self.signup_first_password.setEchoMode(QLineEdit.Password)
        self.signup_first_password.setAlignment(Qt.AlignCenter)
        self.signup_user_name_input = QLineEdit(self.signup_input_frame)
        self.signup_user_name_input.setObjectName(u"signup_user_name_input")
        self.signup_user_name_input.setGeometry(QRect(70, 250, 240, 25))
        self.signup_user_name_input.setMinimumSize(QSize(240, 0))
        self.signup_user_name_input.setMaximumSize(QSize(240, 30))
        self.signup_user_name_input.setFont(font2)
        self.signup_user_name_input.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-bottom:1px solid #000047;}")
        self.signup_user_name_input.setAlignment(Qt.AlignCenter)
        self.user_icon_label_2 = QLabel(self.signup_input_frame)
        self.user_icon_label_2.setObjectName(u"user_icon_label_2")
        self.user_icon_label_2.setGeometry(QRect(90, 0, 200, 180))
        self.user_icon_label_2.setPixmap(QPixmap(u":/user_icon/resource/red_user.svg"))
        self.user_icon_label_2.setScaledContents(True)
        self.signup_welcome = QLabel(self.signup_input_frame)
        self.signup_welcome.setObjectName(u"signup_welcome")
        self.signup_welcome.setGeometry(QRect(0, 180, 380, 60))
        self.signup_welcome.setFont(font3)
        self.signup_welcome.setStyleSheet(u"color: rgb(0, 0, 71);")
        self.signup_welcome.setAlignment(Qt.AlignCenter)
        self.signup_second_password = QLineEdit(self.signup_input_frame)
        self.signup_second_password.setObjectName(u"signup_second_password")
        self.signup_second_password.setGeometry(QRect(90, 370, 200, 25))
        self.signup_second_password.setMinimumSize(QSize(200, 0))
        self.signup_second_password.setMaximumSize(QSize(200, 30))
        self.signup_second_password.setFont(font2)
        self.signup_second_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-bottom:1px solid #000047;}")
        self.signup_second_password.setEchoMode(QLineEdit.Password)
        self.signup_second_password.setAlignment(Qt.AlignCenter)
        self.signup_user_email_input = QLineEdit(self.signup_input_frame)
        self.signup_user_email_input.setObjectName(u"signup_user_email_input")
        self.signup_user_email_input.setGeometry(QRect(60, 290, 260, 25))
        self.signup_user_email_input.setMinimumSize(QSize(260, 0))
        self.signup_user_email_input.setMaximumSize(QSize(260, 30))
        self.signup_user_email_input.setFont(font2)
        self.signup_user_email_input.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-bottom:1px solid #000047;}")
        self.signup_user_email_input.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.signup_input_frame, 0, Qt.AlignHCenter)


        self.horizontalLayout_5.addWidget(self.signup_frame)

        self.middle_stack.addWidget(self.signup_page)
        self.content_page = QWidget()
        self.content_page.setObjectName(u"content_page")
        self.content_page.setStyleSheet(u"border:none;")
        self.horizontalLayout_14 = QHBoxLayout(self.content_page)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.content_frame_container = QFrame(self.content_page)
        self.content_frame_container.setObjectName(u"content_frame_container")
        self.content_frame_container.setStyleSheet(u"border-radius: 15px;")
        self.content_frame_container.setFrameShape(QFrame.NoFrame)
        self.content_frame_container.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_20 = QHBoxLayout(self.content_frame_container)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.left_panel_container = QFrame(self.content_frame_container)
        self.left_panel_container.setObjectName(u"left_panel_container")
        self.left_panel_container.setMinimumSize(QSize(120, 0))
        self.left_panel_container.setMaximumSize(QSize(150, 16777215))
        self.left_panel_container.setFrameShape(QFrame.NoFrame)
        self.left_panel_container.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.left_panel_container)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.left_panel = QFrame(self.left_panel_container)
        self.left_panel.setObjectName(u"left_panel")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.left_panel.sizePolicy().hasHeightForWidth())
        self.left_panel.setSizePolicy(sizePolicy1)
        self.left_panel.setCursor(QCursor(Qt.PointingHandCursor))
        self.left_panel.setStyleSheet(u"background-color: rgb(240, 247, 245);border:1px solid white;")
        self.left_panel.setFrameShape(QFrame.NoFrame)
        self.left_panel.setFrameShadow(QFrame.Raised)
        self.verticalLayout_8 = QVBoxLayout(self.left_panel)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.home_icon_frame = QFrame(self.left_panel)
        self.home_icon_frame.setObjectName(u"home_icon_frame")
        self.home_icon_frame.setMinimumSize(QSize(100, 100))
        self.home_icon_frame.setStyleSheet(u"QFrame{background-color: none;border:none;}QFrame:hover{background-color: rgb(217, 236, 240);}")
        self.home_icon_frame.setFrameShape(QFrame.NoFrame)
        self.home_icon_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_10 = QHBoxLayout(self.home_icon_frame)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(10, 10, 10, 10)
        self.home_icon = QLabel(self.home_icon_frame)
        self.home_icon.setObjectName(u"home_icon")
        self.home_icon.setMinimumSize(QSize(40, 40))
        self.home_icon.setMaximumSize(QSize(50, 50))
        self.home_icon.setSizeIncrement(QSize(1, 1))
        self.home_icon.setPixmap(QPixmap(u":/home_icon/resource/web-house-.svg"))
        self.home_icon.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.home_icon)


        self.verticalLayout_8.addWidget(self.home_icon_frame)

        self.password_icon_frame = QFrame(self.left_panel)
        self.password_icon_frame.setObjectName(u"password_icon_frame")
        self.password_icon_frame.setMinimumSize(QSize(100, 100))
        self.password_icon_frame.setMaximumSize(QSize(16777215, 16777215))
        self.password_icon_frame.setSizeIncrement(QSize(1, 1))
        self.password_icon_frame.setStyleSheet(u"QFrame{background-color: none;border:none;}QFrame:hover{background-color: rgb(217, 236, 240);}")
        self.password_icon_frame.setFrameShape(QFrame.NoFrame)
        self.password_icon_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_11 = QHBoxLayout(self.password_icon_frame)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(8, 10, 12, 10)
        self.password_icon = QLabel(self.password_icon_frame)
        self.password_icon.setObjectName(u"password_icon")
        self.password_icon.setMinimumSize(QSize(50, 40))
        self.password_icon.setMaximumSize(QSize(60, 50))
        self.password_icon.setPixmap(QPixmap(u":/password_icon/resource/lock.svg"))
        self.password_icon.setScaledContents(True)

        self.horizontalLayout_11.addWidget(self.password_icon)


        self.verticalLayout_8.addWidget(self.password_icon_frame)

        self.settings_icon_frame = QFrame(self.left_panel)
        self.settings_icon_frame.setObjectName(u"settings_icon_frame")
        self.settings_icon_frame.setMinimumSize(QSize(100, 100))
        self.settings_icon_frame.setStyleSheet(u"QFrame{background-color:none;border:none;}QFrame:hover{background-color: rgb(217, 236, 240);}")
        self.settings_icon_frame.setFrameShape(QFrame.NoFrame)
        self.settings_icon_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_12 = QHBoxLayout(self.settings_icon_frame)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(10, 10, 10, 10)
        self.settings_icon = QLabel(self.settings_icon_frame)
        self.settings_icon.setObjectName(u"settings_icon")
        self.settings_icon.setMinimumSize(QSize(40, 40))
        self.settings_icon.setMaximumSize(QSize(50, 50))
        self.settings_icon.setPixmap(QPixmap(u":/settings_icon/resource/settings_icon.svg"))
        self.settings_icon.setScaledContents(True)

        self.horizontalLayout_12.addWidget(self.settings_icon)


        self.verticalLayout_8.addWidget(self.settings_icon_frame)


        self.verticalLayout_7.addWidget(self.left_panel, 0, Qt.AlignVCenter)


        self.horizontalLayout_20.addWidget(self.left_panel_container)

        self.content_frame = QFrame(self.content_frame_container)
        self.content_frame.setObjectName(u"content_frame")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.content_frame.sizePolicy().hasHeightForWidth())
        self.content_frame.setSizePolicy(sizePolicy2)
        self.content_frame.setMinimumSize(QSize(0, 0))
        self.content_frame.setMaximumSize(QSize(16777215, 16777215))
        self.content_frame.setStyleSheet(u"")
        self.content_frame.setFrameShape(QFrame.NoFrame)
        self.content_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_18 = QHBoxLayout(self.content_frame)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalLayout_18.setContentsMargins(10, 0, 10, 0)
        self.content_stack = QStackedWidget(self.content_frame)
        self.content_stack.setObjectName(u"content_stack")
        sizePolicy2.setHeightForWidth(self.content_stack.sizePolicy().hasHeightForWidth())
        self.content_stack.setSizePolicy(sizePolicy2)
        self.content_stack.setStyleSheet(u"")
        self.home_page = QWidget()
        self.home_page.setObjectName(u"home_page")
        self.horizontalLayout_13 = QHBoxLayout(self.home_page)
        self.horizontalLayout_13.setSpacing(20)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.password_modify_frame = QFrame(self.home_page)
        self.password_modify_frame.setObjectName(u"password_modify_frame")
        self.password_modify_frame.setFrameShape(QFrame.StyledPanel)
        self.password_modify_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_12 = QVBoxLayout(self.password_modify_frame)
        self.verticalLayout_12.setSpacing(20)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 5, 0, 5)
        self.add_new_password_frame = QFrame(self.password_modify_frame)
        self.add_new_password_frame.setObjectName(u"add_new_password_frame")
        self.add_new_password_frame.setStyleSheet(u"background-color: rgb(240, 247, 245);border:1px solid white;")
        self.add_new_password_frame.setFrameShape(QFrame.StyledPanel)
        self.add_new_password_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_13 = QVBoxLayout(self.add_new_password_frame)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 10, 0, 10)
        self.add_new_password_label = QLabel(self.add_new_password_frame)
        self.add_new_password_label.setObjectName(u"add_new_password_label")
        self.add_new_password_label.setMinimumSize(QSize(0, 100))
        self.add_new_password_label.setMaximumSize(QSize(16777215, 100))
        font5 = QFont()
        font5.setFamily(u"Century Gothic")
        font5.setPointSize(14)
        self.add_new_password_label.setFont(font5)
        self.add_new_password_label.setContextMenuPolicy(Qt.NoContextMenu)
        self.add_new_password_label.setStyleSheet(u"border:none;color: rgb(0, 0, 71);")

        self.verticalLayout_13.addWidget(self.add_new_password_label, 0, Qt.AlignHCenter)

        self.add_new_password_middle_frame = QFrame(self.add_new_password_frame)
        self.add_new_password_middle_frame.setObjectName(u"add_new_password_middle_frame")
        self.add_new_password_middle_frame.setStyleSheet(u"border:none;")
        self.add_new_password_middle_frame.setFrameShape(QFrame.NoFrame)
        self.add_new_password_middle_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_15 = QHBoxLayout(self.add_new_password_middle_frame)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.other_details_frame = QFrame(self.add_new_password_middle_frame)
        self.other_details_frame.setObjectName(u"other_details_frame")
        self.other_details_frame.setFrameShape(QFrame.NoFrame)
        self.other_details_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_14 = QVBoxLayout(self.other_details_frame)
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(10, 0, 10, 0)
        self.new_password_url = QLineEdit(self.other_details_frame)
        self.new_password_url.setObjectName(u"new_password_url")
        self.new_password_url.setMinimumSize(QSize(200, 0))
        self.new_password_url.setMaximumSize(QSize(250, 30))
        self.new_password_url.setFont(font2)
        self.new_password_url.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border-bottom:1px solid #000047;}")
        self.new_password_url.setAlignment(Qt.AlignCenter)

        self.verticalLayout_14.addWidget(self.new_password_url, 0, Qt.AlignHCenter)

        self.new_password_user_name_or_email = QLineEdit(self.other_details_frame)
        self.new_password_user_name_or_email.setObjectName(u"new_password_user_name_or_email")
        self.new_password_user_name_or_email.setMinimumSize(QSize(200, 0))
        self.new_password_user_name_or_email.setMaximumSize(QSize(250, 30))
        self.new_password_user_name_or_email.setFont(font2)
        self.new_password_user_name_or_email.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border-bottom:1px solid #000047;}")
        self.new_password_user_name_or_email.setAlignment(Qt.AlignCenter)

        self.verticalLayout_14.addWidget(self.new_password_user_name_or_email, 0, Qt.AlignHCenter)


        self.horizontalLayout_15.addWidget(self.other_details_frame)

        self.new_password_frame = QFrame(self.add_new_password_middle_frame)
        self.new_password_frame.setObjectName(u"new_password_frame")
        self.new_password_frame.setFrameShape(QFrame.StyledPanel)
        self.new_password_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_15 = QVBoxLayout(self.new_password_frame)
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(10, 0, 10, 0)
        self.new_password = QLineEdit(self.new_password_frame)
        self.new_password.setObjectName(u"new_password")
        self.new_password.setMinimumSize(QSize(200, 0))
        self.new_password.setMaximumSize(QSize(250, 30))
        self.new_password.setFont(font2)
        self.new_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border-bottom:1px solid #000047;}")
        self.new_password.setEchoMode(QLineEdit.Password)
        self.new_password.setAlignment(Qt.AlignCenter)

        self.verticalLayout_15.addWidget(self.new_password, 0, Qt.AlignHCenter)

        self.new_password_strength_slider = QSlider(self.new_password_frame)
        self.new_password_strength_slider.setObjectName(u"new_password_strength_slider")
        self.new_password_strength_slider.setCursor(QCursor(Qt.PointingHandCursor))
        self.new_password_strength_slider.setOrientation(Qt.Horizontal)

        self.verticalLayout_15.addWidget(self.new_password_strength_slider, 0, Qt.AlignHCenter)

        self.generate_new_password = QPushButton(self.new_password_frame)
        self.generate_new_password.setObjectName(u"generate_new_password")
        sizePolicy3 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.generate_new_password.sizePolicy().hasHeightForWidth())
        self.generate_new_password.setSizePolicy(sizePolicy3)
        self.generate_new_password.setMinimumSize(QSize(90, 40))
        self.generate_new_password.setMaximumSize(QSize(220, 40))
        self.generate_new_password.setFont(font4)
        self.generate_new_password.setCursor(QCursor(Qt.PointingHandCursor))
        self.generate_new_password.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(196, 220, 236);}QPushButton:hover{background-color: rgb(172, 193, 207);}")

        self.verticalLayout_15.addWidget(self.generate_new_password, 0, Qt.AlignHCenter)


        self.horizontalLayout_15.addWidget(self.new_password_frame)


        self.verticalLayout_13.addWidget(self.add_new_password_middle_frame)

        self.new_password_submit_button = QPushButton(self.add_new_password_frame)
        self.new_password_submit_button.setObjectName(u"new_password_submit_button")
        self.new_password_submit_button.setMinimumSize(QSize(80, 40))
        self.new_password_submit_button.setMaximumSize(QSize(80, 40))
        self.new_password_submit_button.setFont(font4)
        self.new_password_submit_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.new_password_submit_button.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(34, 197, 32);}QPushButton:hover{background-color: rgb(23, 132, 21);}")

        self.verticalLayout_13.addWidget(self.new_password_submit_button, 0, Qt.AlignHCenter)


        self.verticalLayout_12.addWidget(self.add_new_password_frame)

        self.update_password_frame = QFrame(self.password_modify_frame)
        self.update_password_frame.setObjectName(u"update_password_frame")
        self.update_password_frame.setStyleSheet(u"background-color: rgb(240, 247, 245);border:1px solid white;")
        self.update_password_frame.setFrameShape(QFrame.StyledPanel)
        self.update_password_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_18 = QVBoxLayout(self.update_password_frame)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.verticalLayout_18.setContentsMargins(0, 10, 0, 10)
        self.update_password_label = QLabel(self.update_password_frame)
        self.update_password_label.setObjectName(u"update_password_label")
        self.update_password_label.setMinimumSize(QSize(0, 100))
        self.update_password_label.setMaximumSize(QSize(16777215, 100))
        self.update_password_label.setFont(font5)
        self.update_password_label.setContextMenuPolicy(Qt.NoContextMenu)
        self.update_password_label.setStyleSheet(u"border:none;color: rgb(0, 0, 71);")

        self.verticalLayout_18.addWidget(self.update_password_label, 0, Qt.AlignHCenter)

        self.update_password_middle_frame = QFrame(self.update_password_frame)
        self.update_password_middle_frame.setObjectName(u"update_password_middle_frame")
        self.update_password_middle_frame.setStyleSheet(u"border:none;")
        self.update_password_middle_frame.setFrameShape(QFrame.StyledPanel)
        self.update_password_middle_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_16 = QHBoxLayout(self.update_password_middle_frame)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.input_old_details_frame = QFrame(self.update_password_middle_frame)
        self.input_old_details_frame.setObjectName(u"input_old_details_frame")
        self.input_old_details_frame.setFrameShape(QFrame.StyledPanel)
        self.input_old_details_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_17 = QVBoxLayout(self.input_old_details_frame)
        self.verticalLayout_17.setSpacing(10)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.verticalLayout_17.setContentsMargins(10, 0, 10, 0)
        self.old_url = QLineEdit(self.input_old_details_frame)
        self.old_url.setObjectName(u"old_url")
        self.old_url.setMinimumSize(QSize(200, 0))
        self.old_url.setMaximumSize(QSize(250, 30))
        self.old_url.setFont(font2)
        self.old_url.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border-bottom:1px solid #000047;}")
        self.old_url.setAlignment(Qt.AlignCenter)

        self.verticalLayout_17.addWidget(self.old_url, 0, Qt.AlignHCenter)

        self.old_user_name_or_email = QLineEdit(self.input_old_details_frame)
        self.old_user_name_or_email.setObjectName(u"old_user_name_or_email")
        self.old_user_name_or_email.setMinimumSize(QSize(200, 0))
        self.old_user_name_or_email.setMaximumSize(QSize(250, 30))
        self.old_user_name_or_email.setFont(font2)
        self.old_user_name_or_email.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border-bottom:1px solid #000047;}")
        self.old_user_name_or_email.setAlignment(Qt.AlignCenter)

        self.verticalLayout_17.addWidget(self.old_user_name_or_email, 0, Qt.AlignHCenter)

        self.old_password = QLineEdit(self.input_old_details_frame)
        self.old_password.setObjectName(u"old_password")
        self.old_password.setMinimumSize(QSize(200, 0))
        self.old_password.setMaximumSize(QSize(250, 30))
        self.old_password.setFont(font2)
        self.old_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border-bottom:1px solid #000047;}")
        self.old_password.setEchoMode(QLineEdit.Password)
        self.old_password.setAlignment(Qt.AlignCenter)

        self.verticalLayout_17.addWidget(self.old_password, 0, Qt.AlignHCenter)


        self.horizontalLayout_16.addWidget(self.input_old_details_frame)

        self.update_password_input_frame = QFrame(self.update_password_middle_frame)
        self.update_password_input_frame.setObjectName(u"update_password_input_frame")
        self.update_password_input_frame.setFrameShape(QFrame.StyledPanel)
        self.update_password_input_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_16 = QVBoxLayout(self.update_password_input_frame)
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(10, 0, 10, 0)
        self.updated_password = QLineEdit(self.update_password_input_frame)
        self.updated_password.setObjectName(u"updated_password")
        self.updated_password.setMinimumSize(QSize(200, 0))
        self.updated_password.setMaximumSize(QSize(250, 30))
        self.updated_password.setFont(font2)
        self.updated_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border-bottom:1px solid #000047;}")
        self.updated_password.setEchoMode(QLineEdit.Password)
        self.updated_password.setAlignment(Qt.AlignCenter)

        self.verticalLayout_16.addWidget(self.updated_password, 0, Qt.AlignHCenter)

        self.update_password_strength_slider = QSlider(self.update_password_input_frame)
        self.update_password_strength_slider.setObjectName(u"update_password_strength_slider")
        self.update_password_strength_slider.setCursor(QCursor(Qt.PointingHandCursor))
        self.update_password_strength_slider.setOrientation(Qt.Horizontal)

        self.verticalLayout_16.addWidget(self.update_password_strength_slider, 0, Qt.AlignHCenter)

        self.generate_updated_password = QPushButton(self.update_password_input_frame)
        self.generate_updated_password.setObjectName(u"generate_updated_password")
        sizePolicy3.setHeightForWidth(self.generate_updated_password.sizePolicy().hasHeightForWidth())
        self.generate_updated_password.setSizePolicy(sizePolicy3)
        self.generate_updated_password.setMinimumSize(QSize(90, 40))
        self.generate_updated_password.setMaximumSize(QSize(220, 40))
        self.generate_updated_password.setFont(font4)
        self.generate_updated_password.setCursor(QCursor(Qt.PointingHandCursor))
        self.generate_updated_password.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(196, 220, 236);}QPushButton:hover{background-color: rgb(172, 193, 207);}")

        self.verticalLayout_16.addWidget(self.generate_updated_password, 0, Qt.AlignHCenter)


        self.horizontalLayout_16.addWidget(self.update_password_input_frame)


        self.verticalLayout_18.addWidget(self.update_password_middle_frame)

        self.updated_password_submit_button = QPushButton(self.update_password_frame)
        self.updated_password_submit_button.setObjectName(u"updated_password_submit_button")
        self.updated_password_submit_button.setMinimumSize(QSize(80, 40))
        self.updated_password_submit_button.setMaximumSize(QSize(80, 40))
        self.updated_password_submit_button.setFont(font4)
        self.updated_password_submit_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.updated_password_submit_button.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(34, 197, 32);}QPushButton:hover{background-color: rgb(23, 132, 21);}")

        self.verticalLayout_18.addWidget(self.updated_password_submit_button, 0, Qt.AlignHCenter)


        self.verticalLayout_12.addWidget(self.update_password_frame)


        self.horizontalLayout_13.addWidget(self.password_modify_frame)

        self.password_etc_frame = QFrame(self.home_page)
        self.password_etc_frame.setObjectName(u"password_etc_frame")
        self.password_etc_frame.setFrameShape(QFrame.StyledPanel)
        self.password_etc_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.password_etc_frame)
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 5, 0, 5)
        self.most_used_password_frame = QFrame(self.password_etc_frame)
        self.most_used_password_frame.setObjectName(u"most_used_password_frame")
        self.most_used_password_frame.setStyleSheet(u"background-color: rgb(240, 247, 245);")
        self.most_used_password_frame.setFrameShape(QFrame.StyledPanel)
        self.most_used_password_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.most_used_password_frame)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.most_used_password_label = QLabel(self.most_used_password_frame)
        self.most_used_password_label.setObjectName(u"most_used_password_label")
        self.most_used_password_label.setMinimumSize(QSize(0, 100))
        self.most_used_password_label.setMaximumSize(QSize(16777215, 100))
        self.most_used_password_label.setFont(font5)
        self.most_used_password_label.setStyleSheet(u"color:rgb(0,0,71);")
        self.most_used_password_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.most_used_password_label)


        self.verticalLayout_6.addWidget(self.most_used_password_frame)

        self.password_reports_frame = QFrame(self.password_etc_frame)
        self.password_reports_frame.setObjectName(u"password_reports_frame")
        self.password_reports_frame.setStyleSheet(u"background-color: rgb(240, 247, 245);border:1px solid white;")
        self.password_reports_frame.setFrameShape(QFrame.StyledPanel)
        self.password_reports_frame.setFrameShadow(QFrame.Raised)

        self.verticalLayout_6.addWidget(self.password_reports_frame)


        self.horizontalLayout_13.addWidget(self.password_etc_frame)

        self.content_stack.addWidget(self.home_page)
        self.password_page = QWidget()
        self.password_page.setObjectName(u"password_page")
        self.verticalLayout_10 = QVBoxLayout(self.password_page)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.search_container = QFrame(self.password_page)
        self.search_container.setObjectName(u"search_container")
        self.search_container.setMinimumSize(QSize(0, 100))
        self.search_container.setMaximumSize(QSize(16777215, 150))
        self.search_container.setStyleSheet(u"background-color: rgb(240, 247, 245);border:1px solid white;")
        self.search_container.setFrameShape(QFrame.NoFrame)
        self.search_container.setFrameShadow(QFrame.Raised)
        self.search_this = QLineEdit(self.search_container)
        self.search_this.setObjectName(u"search_this")
        self.search_this.setGeometry(QRect(340, 90, 250, 17))
        self.search_this.setMinimumSize(QSize(200, 0))
        self.search_this.setMaximumSize(QSize(250, 30))
        self.search_this.setFont(font2)
        self.search_this.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border:none;border-bottom:1px solid #000047;}")
        self.search_this.setAlignment(Qt.AlignCenter)
        self.search_button = QPushButton(self.search_container)
        self.search_button.setObjectName(u"search_button")
        self.search_button.setGeometry(QRect(720, 70, 101, 40))
        sizePolicy3.setHeightForWidth(self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(sizePolicy3)
        self.search_button.setMinimumSize(QSize(80, 40))
        self.search_button.setMaximumSize(QSize(220, 40))
        self.search_button.setFont(font4)
        self.search_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.search_button.setStyleSheet(u"QPushButton{border:none;color: rgb(0, 0, 71);background-color: rgb(196, 220, 236);}QPushButton:hover{background-color: rgb(172, 193, 207);}")
        self.search_password_label = QLabel(self.search_container)
        self.search_password_label.setObjectName(u"search_password_label")
        self.search_password_label.setGeometry(QRect(30, 20, 331, 51))
        self.search_password_label.setMinimumSize(QSize(0, 0))
        self.search_password_label.setMaximumSize(QSize(16777215, 16777215))
        self.search_password_label.setFont(font5)
        self.search_password_label.setContextMenuPolicy(Qt.NoContextMenu)
        self.search_password_label.setStyleSheet(u"border:none;color: rgb(0, 0, 71);")

        self.verticalLayout_10.addWidget(self.search_container)

        self.password_list_container = QFrame(self.password_page)
        self.password_list_container.setObjectName(u"password_list_container")
        self.password_list_container.setStyleSheet(u"background-color: rgb(240, 247, 245);border:1px solid white;")
        self.password_list_container.setFrameShape(QFrame.NoFrame)
        self.password_list_container.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.password_list_container)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")

        self.verticalLayout_10.addWidget(self.password_list_container)

        self.content_stack.addWidget(self.password_page)
        self.settings_page = QWidget()
        self.settings_page.setObjectName(u"settings_page")
        self.verticalLayout_11 = QVBoxLayout(self.settings_page)
        self.verticalLayout_11.setSpacing(20)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.account_details_container = QFrame(self.settings_page)
        self.account_details_container.setObjectName(u"account_details_container")
        self.account_details_container.setStyleSheet(u"background-color: rgb(240, 247, 245);border:1px solid white;")
        self.account_details_container.setFrameShape(QFrame.StyledPanel)
        self.account_details_container.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_17 = QHBoxLayout(self.account_details_container)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.user_icon_frame = QFrame(self.account_details_container)
        self.user_icon_frame.setObjectName(u"user_icon_frame")
        self.user_icon_frame.setMinimumSize(QSize(400, 0))
        self.user_icon_frame.setMaximumSize(QSize(400, 16777215))
        self.user_icon_frame.setStyleSheet(u"border:none;")
        self.user_icon_frame.setFrameShape(QFrame.StyledPanel)
        self.user_icon_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_9 = QVBoxLayout(self.user_icon_frame)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.user_icon_label_3 = QLabel(self.user_icon_frame)
        self.user_icon_label_3.setObjectName(u"user_icon_label_3")
        self.user_icon_label_3.setStyleSheet(u"border:1px solid white;")
        self.user_icon_label_3.setPixmap(QPixmap(u":/user_icon/resource/red_user.svg"))
        self.user_icon_label_3.setScaledContents(True)

        self.verticalLayout_9.addWidget(self.user_icon_label_3, 0, Qt.AlignHCenter|Qt.AlignVCenter)


        self.horizontalLayout_17.addWidget(self.user_icon_frame)

        self.user_details_frame = QFrame(self.account_details_container)
        self.user_details_frame.setObjectName(u"user_details_frame")
        self.user_details_frame.setStyleSheet(u"border-radius: 15px;border:none;")
        self.user_details_frame.setFrameShape(QFrame.NoFrame)
        self.user_details_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_19 = QVBoxLayout(self.user_details_frame)
        self.verticalLayout_19.setSpacing(15)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.user_name_details = QLabel(self.user_details_frame)
        self.user_name_details.setObjectName(u"user_name_details")
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.user_name_details.sizePolicy().hasHeightForWidth())
        self.user_name_details.setSizePolicy(sizePolicy4)
        self.user_name_details.setMinimumSize(QSize(0, 30))
        self.user_name_details.setMaximumSize(QSize(200, 40))
        self.user_name_details.setFont(font2)
        self.user_name_details.setStyleSheet(u"color:rgb(0,0,71);border:1px solid white;")
        self.user_name_details.setMargin(0)
        self.user_name_details.setIndent(-1)

        self.verticalLayout_19.addWidget(self.user_name_details)

        self.user_email_details = QLabel(self.user_details_frame)
        self.user_email_details.setObjectName(u"user_email_details")
        self.user_email_details.setMinimumSize(QSize(0, 30))
        self.user_email_details.setMaximumSize(QSize(16777215, 40))
        self.user_email_details.setFont(font2)
        self.user_email_details.setStyleSheet(u"color:rgb(0,0,71);border:1px solid white;")

        self.verticalLayout_19.addWidget(self.user_email_details)

        self.update_data_from_google_button = QPushButton(self.user_details_frame)
        self.update_data_from_google_button.setObjectName(u"update_data_from_google_button")
        self.update_data_from_google_button.setMinimumSize(QSize(80, 40))
        self.update_data_from_google_button.setMaximumSize(QSize(16777215, 40))
        self.update_data_from_google_button.setFont(font4)
        self.update_data_from_google_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.update_data_from_google_button.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(8, 177, 47);border:1px solid white;}QPushButton:hover{background-color: rgb(6, 120, 30);}")

        self.verticalLayout_19.addWidget(self.update_data_from_google_button)


        self.horizontalLayout_17.addWidget(self.user_details_frame)

        self.logout_frame = QFrame(self.account_details_container)
        self.logout_frame.setObjectName(u"logout_frame")
        sizePolicy4.setHeightForWidth(self.logout_frame.sizePolicy().hasHeightForWidth())
        self.logout_frame.setSizePolicy(sizePolicy4)
        self.logout_frame.setMaximumSize(QSize(120, 16777215))
        self.logout_frame.setStyleSheet(u"border:none;")
        self.logout_frame.setFrameShape(QFrame.StyledPanel)
        self.logout_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_20 = QVBoxLayout(self.logout_frame)
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.logout_button = QPushButton(self.logout_frame)
        self.logout_button.setObjectName(u"logout_button")
        sizePolicy5 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.logout_button.sizePolicy().hasHeightForWidth())
        self.logout_button.setSizePolicy(sizePolicy5)
        self.logout_button.setMinimumSize(QSize(100, 40))
        self.logout_button.setMaximumSize(QSize(120, 40))
        self.logout_button.setFont(font4)
        self.logout_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.logout_button.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(184, 7, 19);border:1px solid white;}QPushButton:hover{background-color: rgb(124, 5, 15);}")

        self.verticalLayout_20.addWidget(self.logout_button)


        self.horizontalLayout_17.addWidget(self.logout_frame)

        self.delete_account_frame = QFrame(self.account_details_container)
        self.delete_account_frame.setObjectName(u"delete_account_frame")
        self.delete_account_frame.setStyleSheet(u"border:none;")
        self.delete_account_frame.setFrameShape(QFrame.StyledPanel)
        self.delete_account_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_21 = QVBoxLayout(self.delete_account_frame)
        self.verticalLayout_21.setObjectName(u"verticalLayout_21")
        self.delete_button = QPushButton(self.delete_account_frame)
        self.delete_button.setObjectName(u"delete_button")
        self.delete_button.setMinimumSize(QSize(180, 40))
        self.delete_button.setMaximumSize(QSize(200, 40))
        self.delete_button.setFont(font4)
        self.delete_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.delete_button.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(184, 7, 19);border:1px solid white;}QPushButton:hover{background-color: rgb(124, 5, 15);}")

        self.verticalLayout_21.addWidget(self.delete_button, 0, Qt.AlignHCenter)

        self.label = QLabel(self.delete_account_frame)
        self.label.setObjectName(u"label")
        self.label.setFont(font2)
        self.label.setStyleSheet(u"color:rgb(0,0,71);border:1px solid white;")

        self.verticalLayout_21.addWidget(self.label)


        self.horizontalLayout_17.addWidget(self.delete_account_frame)


        self.verticalLayout_11.addWidget(self.account_details_container)

        self.extra_details_container = QFrame(self.settings_page)
        self.extra_details_container.setObjectName(u"extra_details_container")
        self.extra_details_container.setStyleSheet(u"background-color: rgb(240, 247, 245);border:1px solid white;")
        self.extra_details_container.setFrameShape(QFrame.StyledPanel)
        self.extra_details_container.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_19 = QHBoxLayout(self.extra_details_container)
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.change_master_password_container = QFrame(self.extra_details_container)
        self.change_master_password_container.setObjectName(u"change_master_password_container")
        self.change_master_password_container.setStyleSheet(u"border:none;")
        self.change_master_password_container.setFrameShape(QFrame.NoFrame)
        self.change_master_password_container.setFrameShadow(QFrame.Raised)
        self.verticalLayout_22 = QVBoxLayout(self.change_master_password_container)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName(u"verticalLayout_22")
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.change_master_password_label = QLabel(self.change_master_password_container)
        self.change_master_password_label.setObjectName(u"change_master_password_label")
        self.change_master_password_label.setMaximumSize(QSize(16777215, 50))
        self.change_master_password_label.setFont(font5)
        self.change_master_password_label.setStyleSheet(u"color:rgb(0,0,71);border:none;")
        self.change_master_password_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_22.addWidget(self.change_master_password_label)

        self.change_master_password_frame = QFrame(self.change_master_password_container)
        self.change_master_password_frame.setObjectName(u"change_master_password_frame")
        self.change_master_password_frame.setStyleSheet(u"")
        self.change_master_password_frame.setFrameShape(QFrame.NoFrame)
        self.change_master_password_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_21 = QHBoxLayout(self.change_master_password_frame)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.old_master_password_frame = QFrame(self.change_master_password_frame)
        self.old_master_password_frame.setObjectName(u"old_master_password_frame")
        sizePolicy4.setHeightForWidth(self.old_master_password_frame.sizePolicy().hasHeightForWidth())
        self.old_master_password_frame.setSizePolicy(sizePolicy4)
        self.old_master_password_frame.setMinimumSize(QSize(200, 0))
        self.old_master_password_frame.setMaximumSize(QSize(250, 16777215))
        self.old_master_password_frame.setFrameShape(QFrame.StyledPanel)
        self.old_master_password_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_23 = QVBoxLayout(self.old_master_password_frame)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName(u"verticalLayout_23")
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.old_master_password = QLineEdit(self.old_master_password_frame)
        self.old_master_password.setObjectName(u"old_master_password")
        self.old_master_password.setMinimumSize(QSize(200, 0))
        self.old_master_password.setMaximumSize(QSize(250, 30))
        self.old_master_password.setFont(font2)
        self.old_master_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border:none;border-bottom:1px solid #000047;}")
        self.old_master_password.setAlignment(Qt.AlignCenter)

        self.verticalLayout_23.addWidget(self.old_master_password)


        self.horizontalLayout_21.addWidget(self.old_master_password_frame)

        self.new_master_password_frame = QFrame(self.change_master_password_frame)
        self.new_master_password_frame.setObjectName(u"new_master_password_frame")
        self.new_master_password_frame.setMinimumSize(QSize(200, 0))
        self.new_master_password_frame.setMaximumSize(QSize(250, 16777215))
        self.new_master_password_frame.setFrameShape(QFrame.StyledPanel)
        self.new_master_password_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_24 = QVBoxLayout(self.new_master_password_frame)
        self.verticalLayout_24.setSpacing(10)
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.first_update_password = QLineEdit(self.new_master_password_frame)
        self.first_update_password.setObjectName(u"first_update_password")
        self.first_update_password.setMinimumSize(QSize(200, 0))
        self.first_update_password.setMaximumSize(QSize(250, 30))
        self.first_update_password.setFont(font2)
        self.first_update_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border:none;border-bottom:1px solid #000047;}")
        self.first_update_password.setAlignment(Qt.AlignCenter)

        self.verticalLayout_24.addWidget(self.first_update_password)

        self.second_update_password = QLineEdit(self.new_master_password_frame)
        self.second_update_password.setObjectName(u"second_update_password")
        self.second_update_password.setMinimumSize(QSize(200, 0))
        self.second_update_password.setMaximumSize(QSize(250, 30))
        self.second_update_password.setFont(font2)
        self.second_update_password.setStyleSheet(u"QLineEdit{color: rgb(0, 0, 71);border-radius:none;border:none;border-bottom:1px solid #000047;}")
        self.second_update_password.setAlignment(Qt.AlignCenter)
        self.second_update_password.setReadOnly(False)

        self.verticalLayout_24.addWidget(self.second_update_password)


        self.horizontalLayout_21.addWidget(self.new_master_password_frame)

        self.frame_6 = QFrame(self.change_master_password_frame)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setMaximumSize(QSize(120, 16777215))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.verticalLayout_25 = QVBoxLayout(self.frame_6)
        self.verticalLayout_25.setObjectName(u"verticalLayout_25")
        self.update_password_button = QPushButton(self.frame_6)
        self.update_password_button.setObjectName(u"update_password_button")
        self.update_password_button.setMinimumSize(QSize(80, 40))
        self.update_password_button.setMaximumSize(QSize(120, 40))
        self.update_password_button.setFont(font4)
        self.update_password_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.update_password_button.setStyleSheet(u"QPushButton{color: rgb(0, 0, 71);background-color: rgb(8, 177, 47);}QPushButton:hover{background-color: rgb(6, 120, 30);}")

        self.verticalLayout_25.addWidget(self.update_password_button)


        self.horizontalLayout_21.addWidget(self.frame_6)


        self.verticalLayout_22.addWidget(self.change_master_password_frame)


        self.horizontalLayout_19.addWidget(self.change_master_password_container)

        self.about_the_author_frame = QFrame(self.extra_details_container)
        self.about_the_author_frame.setObjectName(u"about_the_author_frame")
        self.about_the_author_frame.setMinimumSize(QSize(400, 0))
        self.about_the_author_frame.setStyleSheet(u"border:none;")
        self.about_the_author_frame.setFrameShape(QFrame.StyledPanel)
        self.about_the_author_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_26 = QVBoxLayout(self.about_the_author_frame)
        self.verticalLayout_26.setSpacing(10)
        self.verticalLayout_26.setObjectName(u"verticalLayout_26")
        self.verticalLayout_26.setContentsMargins(20, 0, 20, 10)
        self.about_the_author_top_label = QLabel(self.about_the_author_frame)
        self.about_the_author_top_label.setObjectName(u"about_the_author_top_label")
        self.about_the_author_top_label.setFont(font5)
        self.about_the_author_top_label.setStyleSheet(u"border:none;color:rgb(0,0,71);")

        self.verticalLayout_26.addWidget(self.about_the_author_top_label)

        self.about_the_author_content_label = QLabel(self.about_the_author_frame)
        self.about_the_author_content_label.setObjectName(u"about_the_author_content_label")
        self.about_the_author_content_label.setFont(font2)
        self.about_the_author_content_label.setStyleSheet(u"color:rgb(0,0,71);")

        self.verticalLayout_26.addWidget(self.about_the_author_content_label)


        self.horizontalLayout_19.addWidget(self.about_the_author_frame)


        self.verticalLayout_11.addWidget(self.extra_details_container)

        self.content_stack.addWidget(self.settings_page)

        self.horizontalLayout_18.addWidget(self.content_stack)


        self.horizontalLayout_20.addWidget(self.content_frame)


        self.horizontalLayout_14.addWidget(self.content_frame_container)

        self.middle_stack.addWidget(self.content_page)

        self.verticalLayout.addWidget(self.middle_stack)

        self.bottom_frame = QFrame(self.outer_frame)
        self.bottom_frame.setObjectName(u"bottom_frame")
        self.bottom_frame.setMaximumSize(QSize(16777215, 50))
        self.bottom_frame.setStyleSheet(u"border:1px solid white;")
        self.bottom_frame.setFrameShape(QFrame.NoFrame)
        self.bottom_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(10, 0, 0, 0)
        self.credit_frame = QFrame(self.bottom_frame)
        self.credit_frame.setObjectName(u"credit_frame")
        self.credit_frame.setStyleSheet(u"border:none;")
        self.credit_frame.setFrameShape(QFrame.NoFrame)
        self.credit_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_7 = QHBoxLayout(self.credit_frame)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(10, 0, 0, 0)
        self.credit_label = QLabel(self.credit_frame)
        self.credit_label.setObjectName(u"credit_label")
        font6 = QFont()
        font6.setFamily(u"Rage Italic")
        font6.setPointSize(12)
        self.credit_label.setFont(font6)
        self.credit_label.setStyleSheet(u"color: rgb(0, 0, 71);")
        self.credit_label.setFrameShape(QFrame.NoFrame)

        self.horizontalLayout_7.addWidget(self.credit_label)

        self.empty_credit_label = QLabel(self.credit_frame)
        self.empty_credit_label.setObjectName(u"empty_credit_label")

        self.horizontalLayout_7.addWidget(self.empty_credit_label)


        self.horizontalLayout_6.addWidget(self.credit_frame)

        self.resize_frame = QFrame(self.bottom_frame)
        self.resize_frame.setObjectName(u"resize_frame")
        self.resize_frame.setStyleSheet(u"border:none;")
        self.resize_frame.setFrameShape(QFrame.NoFrame)
        self.resize_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_8 = QHBoxLayout(self.resize_frame)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.resize_label = QLabel(self.resize_frame)
        self.resize_label.setObjectName(u"resize_label")
        self.resize_label.setMinimumSize(QSize(0, 30))
        self.resize_label.setMaximumSize(QSize(30, 16777215))
        self.resize_label.setPixmap(QPixmap(u":/resize_icon/resource/resize_icon.png"))
        self.resize_label.setScaledContents(True)

        self.horizontalLayout_8.addWidget(self.resize_label)


        self.horizontalLayout_6.addWidget(self.resize_frame, 0, Qt.AlignRight|Qt.AlignBottom)


        self.verticalLayout.addWidget(self.bottom_frame)


        self.outer_layout.addWidget(self.outer_frame)

        AlohaMora.setCentralWidget(self.centralwidget)

        self.retranslateUi(AlohaMora)

        self.middle_stack.setCurrentIndex(2)
        self.content_stack.setCurrentIndex(1)

        self.loadLabels()

        QMetaObject.connectSlotsByName(AlohaMora)
    # setupUi

#  Frame Size change when maximized
#--------------------------------------------------------------------------------------------------#
    def toggleLeftPannel(self, status):
        if status == 0:
            # While maximizing
            self.left_panel_container.setMinimumSize(QSize(250, 0))
            self.left_panel_container.setMaximumSize(QSize(250, 16777215))
            self.home_label.setParent(self.home_icon_frame)
            self.horizontalLayout_10.addWidget(self.home_label, 0, Qt.AlignVCenter)
            self.password_label.setParent(self.password_icon_frame)
            self.horizontalLayout_11.addWidget(self.password_label, 0, Qt.AlignVCenter)
            self.settings_label.setParent(self.settings_icon_frame)
            self.horizontalLayout_12.addWidget(self.settings_label, 0, Qt.AlignVCenter)
        else:
            # if already maximized
            self.home_label.setParent(None)
            self.password_label.setParent(None)
            self.settings_label.setParent(None)
            self.left_panel_container.setMinimumSize(QSize(120, 0))
            self.left_panel_container.setMaximumSize(QSize(150, 16777215))

#  Create virtual labels to use. 
#  Add this function in main_ui setup. self.loadLabels()
#--------------------------------------------------------------------------------------------------#
    def loadLabels(self):
            self.left_panel_font = QFont()
            self.left_panel_font.setFamily(u"Cambria")
            self.left_panel_font.setPointSize(10)
            self.left_panel_font.setBold(True)
            
            self.home_label = QLabel()
            self.home_label.setObjectName(u"home_label")
            self.home_label.setMinimumSize(QSize(100, 0))
            self.home_label.setMaximumSize(QSize(100, 16777215))
            self.home_label.setFont(self.left_panel_font)
            self.home_label.setStyleSheet(u"color: rgb(0, 0, 71);")
            self.home_label.setText("Home")    
        
            self.password_label = QLabel()
            self.password_label.setObjectName(u"password_label")
            self.password_label.setMinimumSize(QSize(100, 0))
            self.password_label.setMaximumSize(QSize(100, 16777215))
            self.password_label.setFont(self.left_panel_font)
            self.password_label.setStyleSheet(u"color: rgb(0, 0, 71);")
            self.password_label.setText("Passwords")

            self.settings_label = QLabel()
            self.settings_label.setObjectName(u"password_label")
            self.settings_label.setMinimumSize(QSize(100, 0))
            self.settings_label.setMaximumSize(QSize(100, 16777215))
            self.settings_label.setFont(self.left_panel_font)
            self.settings_label.setStyleSheet(u"color: rgb(0, 0, 71);")
            self.settings_label.setText("Settings")

    def retranslateUi(self, AlohaMora):
        AlohaMora.setWindowTitle(QCoreApplication.translate("AlohaMora", u"AlohaMora", None))
        AlohaMora.setStyleSheet("")
        self.logo_label.setText(QCoreApplication.translate("AlohaMora", u"Aloha Mora ", None))
        self.top_empty_label.setText("")
        self.maximize_button.setText("")
        self.minimize_button.setText("")
        self.close_button.setText("")
        self.login_button.setText(QCoreApplication.translate("AlohaMora", u"LOG IN", None))
        self.login_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"password", None))
        self.user_email_input.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"email id", None))
        self.user_icon_label.setText("")
        self.login_welcome.setText(QCoreApplication.translate("AlohaMora", u"Welcome Back !", None))
        self.signup_option.setText(QCoreApplication.translate("AlohaMora", u"<html><head/><body><p><span style=\" text-decoration: underline;\">new user ? Sign up here</span></p></body></html>", None))
        self.signup_button.setText(QCoreApplication.translate("AlohaMora", u"SIGN UP", None))
        self.signup_first_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"password", None))
        self.signup_user_name_input.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"User name", None))
        self.user_icon_label_2.setText("")
        self.signup_welcome.setText(QCoreApplication.translate("AlohaMora", u"Welcome !", None))
        self.signup_second_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"confirm password", None))
        self.signup_user_email_input.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"email id", None))
        self.home_icon.setText("")
        self.password_icon.setText("")
        self.settings_icon.setText("")
        self.add_new_password_label.setText(QCoreApplication.translate("AlohaMora", u"<html><head/><body><p>Add new password</p></body></html>", None))
        self.new_password_url.setText("")
        self.new_password_url.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"URL", None))
        self.new_password_user_name_or_email.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"User name / email", None))
        self.new_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"password", None))
        self.generate_new_password.setText(QCoreApplication.translate("AlohaMora", u"Generate password !", None))
        self.new_password_submit_button.setText(QCoreApplication.translate("AlohaMora", u"Submit", None))
        self.update_password_label.setText(QCoreApplication.translate("AlohaMora", u"<html><head/><body><p>Update password</p></body></html>", None))
        self.old_url.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"old URL", None))
        self.old_user_name_or_email.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"old user name / email", None))
        self.old_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"old password", None))
        self.updated_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"new password", None))
        self.generate_updated_password.setText(QCoreApplication.translate("AlohaMora", u"Generate password !", None))
        self.updated_password_submit_button.setText(QCoreApplication.translate("AlohaMora", u"Submit", None))
        self.most_used_password_label.setText(QCoreApplication.translate("AlohaMora", u"Most used passwords", None))
        self.search_this.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"URL / user name", None))
        self.search_button.setText(QCoreApplication.translate("AlohaMora", u"Search", None))
        self.search_password_label.setText(QCoreApplication.translate("AlohaMora", u"<html><head/><body><p>Search password</p></body></html>", None))
        self.user_icon_label_3.setText("")
        self.user_name_details.setText(QCoreApplication.translate("AlohaMora", u" Kaushik Biswas", None))
        self.user_email_details.setText(QCoreApplication.translate("AlohaMora", u" kaushik.biswas.15@gmail.com", None))
        self.update_data_from_google_button.setText(QCoreApplication.translate("AlohaMora", u"Reload data from google account", None))
        self.logout_button.setText(QCoreApplication.translate("AlohaMora", u"Log out", None))
        self.delete_button.setText(QCoreApplication.translate("AlohaMora", u"Delete Account", None))
        self.label.setText(QCoreApplication.translate("AlohaMora", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#820000;\">CAUTION !</span></p><p align=\"center\"><br/></p><p align=\"center\">If you delete the account </p><p align=\"center\">all your data will be erased permanently!</p></body></html>", None))
        self.change_master_password_label.setText(QCoreApplication.translate("AlohaMora", u"Change your master password", None))
        self.old_master_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"old password", None))
        self.first_update_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"new password", None))
        self.second_update_password.setPlaceholderText(QCoreApplication.translate("AlohaMora", u"confirm new password", None))
        self.update_password_button.setText(QCoreApplication.translate("AlohaMora", u"Update", None))
        self.about_the_author_top_label.setText(QCoreApplication.translate("AlohaMora", u"Note from the creator...", None))
        self.about_the_author_content_label.setText(QCoreApplication.translate("AlohaMora", u"<html><head/><body><p>Hi !</p><p>I am Kaushik. Thank you very much for considering </p><p>AlohaMora as your password manager. To be honest </p><p>I am creating AlohaMora because I needed one and </p><p>didn't wanna pay for one. But if this helps others as </p><p>well, even better! I have a couple of upgrades planned</p><p>for this software like a chrome extension/mobile version. </p><p>Checkout those if you like. </p><p>Feel free to drop an email and say hi.</p><p><br/></p><p>Kaushik Biswas</p><p>kaushik.biswas.15@gmail.com</p></body></html>", None))
        self.credit_label.setText(QCoreApplication.translate("AlohaMora", u"By: @Kaushik498", None))
        self.empty_credit_label.setText("")
        self.resize_label.setText("")
    # retranslateUi

